import { ArrowLeftOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Col, Form, Input, InputNumber, Result, Row, Select, Skeleton, message } from "antd";
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { PageContainer } from "../../components/page-container/PageContainer.jsx";
import { useGetAllMembersQuery } from "../members/membersApi.js";
import { useGetLoanByIdQuery, useUpdateLoanMutation } from "./loansApi.js";

export function EditLoanPage() {
  const navigate = useNavigate(); const { id } = useParams(); const [form] = Form.useForm(); const [formError, setFormError] = useState("");
  const { data, isLoading, isError, error } = useGetLoanByIdQuery(id, { skip: !id });
  const { data: membersResponse, isLoading: membersLoading } = useGetAllMembersQuery({ page: 1, limit: 100, status: "ACTIVE", sortBy: "fullName", sortOrder: "asc" });
  const [updateLoan, { isLoading: isUpdating }] = useUpdateLoanMutation(); const loan = data?.data;
  const memberOptions = useMemo(() => (membersResponse?.data ?? []).map((member) => ({ value: member.id, label: `${member.fullName} (${member.memberId || "Pending ID"})` })), [membersResponse?.data]);
  if (isLoading) return <PageContainer><Card><Skeleton active paragraph={{ rows: 9 }} /></Card></PageContainer>;
  if (isError || !loan) return <PageContainer><Result status={error?.status === 404 ? "404" : "error"} title="Unable to edit loan" subTitle={error?.data?.message || "Loan not found."} extra={<Button onClick={() => navigate("/loans")}>Back to Loans</Button>} /></PageContainer>;
  if (loan.status !== "PENDING") return <PageContainer><Result status="warning" title="This loan cannot be edited" subTitle="Only pending loans can be edited." extra={<Button type="primary" onClick={() => navigate(`/loans/${loan.id}`)}>Back to Loan</Button>} /></PageContainer>;
  const submit = async (values) => { setFormError(""); try { await updateLoan({ id, payload: values }).unwrap(); message.success("Loan updated successfully"); navigate(`/loans/${id}`); } catch (requestError) { setFormError(requestError?.data?.message || "Unable to update the loan."); } };
  return <PageContainer><div className="loan-page-heading"><Button type="text" icon={<ArrowLeftOutlined />} onClick={() => navigate(`/loans/${id}`)}>Back to Loan</Button></div>{formError && <Alert type="error" showIcon message="Failed to update loan" description={formError} style={{ marginBottom: 16 }} />}<Form form={form} layout="vertical" initialValues={{ memberId: loan.memberId, principalAmount: Number(loan.principalAmount), chargeType: loan.chargeType, chargeValue: Number(loan.chargeValue), installmentCount: loan.installmentCount, frequency: loan.frequency, purpose: loan.purpose, notes: loan.notes }} onFinish={submit}><Row gutter={[16, 16]}><Col xs={24} lg={16}><Card title="Edit Pending Loan" className="member-profile-card"><Row gutter={[16, 0]}><Col xs={24}><Form.Item name="memberId" label="Member" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" loading={membersLoading} options={memberOptions} /></Form.Item></Col><Col xs={24} md={12}><Form.Item name="principalAmount" label="Principal Amount" rules={[{ required: true }]}><InputNumber className="full-width-control" min={0.01} precision={2} prefix="৳" /></Form.Item></Col><Col xs={24} md={12}><Form.Item name="installmentCount" label="Installment Count" rules={[{ required: true }]}><InputNumber className="full-width-control" min={1} precision={0} /></Form.Item></Col><Col xs={24} md={12}><Form.Item name="chargeType" label="Charge Type"><Select options={[{ value: "PERCENTAGE", label: "Percentage" }, { value: "FLAT", label: "Flat amount" }]} /></Form.Item></Col><Col xs={24} md={12}><Form.Item name="chargeValue" label="Charge Value" rules={[{ required: true }]}><InputNumber className="full-width-control" min={0} precision={2} /></Form.Item></Col><Col xs={24} md={12}><Form.Item name="frequency" label="Frequency"><Select options={[{ value: "MONTHLY", label: "Monthly" }, { value: "WEEKLY", label: "Weekly" }]} /></Form.Item></Col><Col xs={24} md={12}><Form.Item name="purpose" label="Purpose"><Input /></Form.Item></Col><Col xs={24}><Form.Item name="notes" label="Notes"><Input.TextArea rows={4} /></Form.Item></Col></Row></Card></Col><Col xs={24} lg={8}><Card title="Recalculation" className="loan-summary-card">Financial changes are recalculated by the backend using the lower-৳10 installment rule.<Button block type="primary" htmlType="submit" loading={isUpdating} style={{ marginTop: 16 }}>Save Changes</Button></Card></Col></Row></Form></PageContainer>;
}
